// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/stock-exchange": {
            "get": {
                "description": "Lista os últimos 100 registros de criptomoedas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StockExchange"
                ],
                "summary": "Lista todos os registros",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.StockExchange"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro ao buscar registros",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Cria um novo registro de criptomoeda",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StockExchange"
                ],
                "summary": "Cria um novo registro",
                "parameters": [
                    {
                        "description": "Dados da criptomoeda",
                        "name": "stockExchange",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.StockExchange"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.StockExchange"
                        }
                    },
                    "400": {
                        "description": "Erro nos dados enviados",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/stock-exchange/{id}": {
            "get": {
                "description": "Busca um registro de criptomoeda pelo ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StockExchange"
                ],
                "summary": "Busca um registro",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "StockExchange ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StockExchange"
                        }
                    },
                    "404": {
                        "description": "Registro não encontrado",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Atualiza um registro de criptomoeda",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StockExchange"
                ],
                "summary": "Atualiza um registro",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "StockExchange ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados atualizados",
                        "name": "stockExchange",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.StockExchange"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StockExchange"
                        }
                    },
                    "404": {
                        "description": "Registro não encontrado",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove um registro de criptomoeda",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StockExchange"
                ],
                "summary": "Remove um registro",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "StockExchange ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Registro deletado com sucesso",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Registro não encontrado",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/app/pesquisa/{symbol}": {
            "get": {
                "description": "Retorna preços mínimos, máximos e médias dos últimos 21 dias",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pesquisa"
                ],
                "summary": "Pesquisa estatísticas de criptomoedas",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Símbolo da criptomoeda (ex: BTC, ETH)",
                        "name": "symbol",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.CryptoStats"
                        }
                    },
                    "400": {
                        "description": "Símbolo inválido",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erro ao buscar estatísticas",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.CryptoStats": {
            "type": "object",
            "properties": {
                "max_price": {
                    "description": "Preço máximo registrado no período",
                    "type": "number",
                    "example": 45000.75
                },
                "media_maxima": {
                    "description": "Média dos preços máximos diários",
                    "type": "number",
                    "example": 44500.8
                },
                "media_minima": {
                    "description": "Média dos preços mínimos diários",
                    "type": "number",
                    "example": 43000.25
                },
                "min_price": {
                    "description": "Preço mínimo registrado no período",
                    "type": "number",
                    "example": 42000.5
                }
            }
        },
        "models.StockExchange": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "Data e hora de criação do registro",
                    "type": "string",
                    "example": "2025-05-10 15:58:00"
                },
                "id": {
                    "description": "ID único da criptomoeda",
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "description": "Nome da criptomoeda",
                    "type": "string",
                    "example": "Bitcoin"
                },
                "price": {
                    "description": "Preço atual em USD",
                    "type": "number",
                    "example": 45000.5
                },
                "symbol": {
                    "description": "Símbolo da criptomoeda",
                    "type": "string",
                    "example": "BTC"
                },
                "valor": {
                    "description": "Valor em BRL",
                    "type": "number",
                    "example": 225000.75
                }
            }
        }
    },
    "tags": [
        {
            "description": "Operações com criptomoedas",
            "name": "StockExchange"
        },
        {
            "description": "Consultas e estatísticas",
            "name": "Pesquisa"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3030",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "API de Criptomoedas",
	Description:      "API para gerenciamento de dados de criptomoedas",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
